# Generated by Django 4.2.5 on 2023-09-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(null=True)),
                ('subject_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.TextField(null=True)),
                ('student_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('assessment_areas', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=250)),
                ('sydney_participants', models.IntegerField()),
                ('sydney_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer', models.CharField(max_length=255)),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('participant', models.CharField(max_length=255)),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year_level', models.CharField(max_length=50)),
            ],
        ),
    ]
